# Generated by Django 4.0.4 on 2022-05-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_feature_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='events/events/'),
        ),
    ]
